steps:
- name: 'gcr.io/cloud-builders/docker'
  dir: '.'
  args:
  - build
  - '-t'
  - '${_DOCKER_TAG}'
  - '--cache-from'
  - '${_DOCKER_TAG}'
  - '--build-arg'
  - 'EXTRA_DEPS=${_EXTRA_DEPS}'
  - '.'
timeout: 1200s

images: ['${_DOCKER_TAG}']
